Update page.tsx
corrected error - 
Running build in Washington, D.C., USA (East) – iad1 (Hive)
Cloning github.com/rajathooda/butterbot-Rajat-Update (Branch: v7forfeedback, Commit: d84dcf8)
Skipping build cache, deployment was triggered without cache.
Cloning completed: 529.808ms
Running "vercel build"
Vercel CLI 31.2.2
Installing dependencies...
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
> next13-ai-saas@0.1.0 postinstall
> prisma generate
Prisma schema loaded from prisma/schema.prisma
✔ Generated Prisma Client (5.0.0 | library) to ./node_modules/@prisma/client in 67ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
added 924 packages in 32s
210 packages are looking for funding
  run `npm fund` for details
Detected Next.js version: 13.4.9
Detected `package-lock.json` generated by npm 7+...
Running "npm run build"
> next13-ai-saas@0.1.0 build
> next build
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
- info Creating an optimized production build...
- warn Compiled with warnings
./node_modules/@clerk/shared/dist/esm/utils/localStorageBroadcastChannel.js
A Node.js API is used (MessageEvent at line: 23) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
Import trace for requested module:
./node_modules/@clerk/shared/dist/esm/utils/localStorageBroadcastChannel.js
./node_modules/@clerk/shared/dist/esm/utils/index.js
./node_modules/@clerk/shared/dist/esm/index.js
./node_modules/@clerk/clerk-react/dist/esm/errors.js
./node_modules/@clerk/clerk-react/dist/esm/index.js
./node_modules/@clerk/nextjs/dist/esm/client-boundary/controlComponents.js
./node_modules/@clerk/nextjs/dist/esm/index.js
./node_modules/scheduler/cjs/scheduler.production.min.js
A Node.js API is used (setImmediate at line: 51) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
Import trace for requested module:
./node_modules/scheduler/cjs/scheduler.production.min.js
./node_modules/scheduler/index.js
./node_modules/react-dom/cjs/react-dom.production.min.js
./node_modules/react-dom/index.js
./node_modules/next/dist/esm/client/script.js
./node_modules/next/dist/esm/shared/lib/router/router.js
./node_modules/next/dist/esm/client/router.js
./node_modules/next/router.js
./node_modules/@clerk/nextjs/dist/esm/pages/ClerkProvider.js
./node_modules/@clerk/nextjs/dist/esm/components.client.js
./node_modules/@clerk/nextjs/dist/esm/index.js
./node_modules/scheduler/cjs/scheduler.production.min.js
A Node.js API is used (setImmediate at line: 51) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
Import trace for requested module:
./node_modules/scheduler/cjs/scheduler.production.min.js
./node_modules/scheduler/index.js
./node_modules/react-dom/cjs/react-dom.production.min.js
./node_modules/react-dom/index.js
./node_modules/next/dist/esm/client/script.js
./node_modules/next/dist/esm/shared/lib/router/router.js
./node_modules/next/dist/esm/client/router.js
./node_modules/next/router.js
./node_modules/@clerk/nextjs/dist/esm/pages/ClerkProvider.js
./node_modules/@clerk/nextjs/dist/esm/components.client.js
./node_modules/@clerk/nextjs/dist/esm/index.js
./node_modules/scheduler/cjs/scheduler.production.min.js
A Node.js API is used (MessageChannel at line: 120) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
Import trace for requested module:
./node_modules/scheduler/cjs/scheduler.production.min.js
./node_modules/scheduler/index.js
./node_modules/react-dom/cjs/react-dom.production.min.js
./node_modules/react-dom/index.js
./node_modules/next/dist/esm/client/script.js
./node_modules/next/dist/esm/shared/lib/router/router.js
./node_modules/next/dist/esm/client/router.js
./node_modules/next/router.js
./node_modules/@clerk/nextjs/dist/esm/pages/ClerkProvider.js
./node_modules/@clerk/nextjs/dist/esm/components.client.js
./node_modules/@clerk/nextjs/dist/esm/index.js
./node_modules/scheduler/cjs/scheduler.production.min.js
A Node.js API is used (MessageChannel at line: 121) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
Import trace for requested module:
./node_modules/scheduler/cjs/scheduler.production.min.js
./node_modules/scheduler/index.js
./node_modules/react-dom/cjs/react-dom.production.min.js
./node_modules/react-dom/index.js
./node_modules/next/dist/esm/client/script.js
./node_modules/next/dist/esm/shared/lib/router/router.js
./node_modules/next/dist/esm/client/router.js
./node_modules/next/router.js
./node_modules/@clerk/nextjs/dist/esm/pages/ClerkProvider.js
./node_modules/@clerk/nextjs/dist/esm/components.client.js
./node_modules/@clerk/nextjs/dist/esm/index.js
- info Linting and checking validity of types...
Failed to compile.
./app/(dashboard)/(routes)/customise/page.tsx
74:6  Warning: React Hook useEffect has a missing dependency: 'setColorPickerOpen'. Either include it or remove the dependency array. If 'setColorPickerOpen' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps
./app/(dashboard)/(routes)/editbot/page.tsx
168:30  Error: Comments inside children section of tag should be placed inside braces  react/jsx-no-comment-textnodes
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Error: Command "npm run build" exited with 1